#!/usr/bin/env bash

# TODO get current branch

set -e

# are we in a mercurial repo?
if [ ! -d ".hg" ]; then
  echo "Not a mercurial repository."
  exit 1
fi

# get remote (default remote)
# TODO allow users to choose the remote
remote=$(hg paths default)

# set remote url
# TODO handle all available services (github, bitbucket,...)
if [ ${remote:0:3} = 'ssh' ] || [ ${remote:0:5} = 'https' ]; then
    url="https://bitbucket.org/${remote##*org}"
fi

# get current open browser command
case $( uname -s ) in
  Darwin)  open=open;;
  MINGW*)  open=start;;
  CYGWIN*) open=cygstart;;
  MSYS*)   open="powershell.exe –NoProfile Start";;
  *)       open=${BROWSER:-xdg-open};;
esac

# open it in a browser
$open "$url" &> /dev/null
exit 0
