#!/usr/bin/env bash

# This script will open your project's page on bitbucket.com

set -e

# usage info
usage() {
  cat <<EOF
  Usage: hgo [options]
  Options:
    -d, --directory         Add directory to open.
    -b, --branch            Search for current/specific(passed as argument) branch.
    -c, --commit            Open commits' page.
    -v, --version           Output version
    -h, --help              This message.
    --                      End of options
EOF
}

version="0.0.1"
COMMIT=false
PR=false
BRANCH=""
DIRECTORY=""

# parse options
while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
  case $1 in
    -v | --version )
      echo $version
      exit
      ;;
    -d | --directory )
      DIRECTORY="$2"
      shift;
      ;;
    -b | --branch )
      if [[ -n "$2" ]] && [[ ! "$2" =~ ^- ]]; then
        BRANCH="$2"
        shift;
      else
        BRANCH=$(hg branch)
      fi
      ;;
    -c | --commit )
      COMMIT=true
      ;;
    -p | --pull )
      PR=true
      ;;
    -h | --help )
      usage
      exit
      ;;
    * )
      echo "abort: unknown argument" 1>&2
      exit 1
  esac
  shift
done
if [[ "$1" == "--" ]]; then shift; fi


# go under the selected directory
if [ -n "$DIRECTORY" ]; then
  cd $DIRECTORY &> /dev/null
fi

# are we in a mercurial repo?
if [ ! -d ".hg" ]; then
  echo "abort: not a mercurial repository." 1>&2
  exit 1
fi

# get remote (default remote)
# TODO allow users to choose the remote
remote=$(hg paths default)

# set remote url
# TODO handle all available services
if [ ${remote:0:3} = 'ssh' ] || [ ${remote:0:5} = 'https' ]; then
    url="https://bitbucket.org/${remote##*org\/}"
fi

# open according arguments
if [[ -n $BRANCH ]]; then
  url+="/branch/$BRANCH"
elif [[ $COMMIT = true ]]; then
  url+="/commits/all"
elif [[ $PR = true ]]; then
  url+="/pull-requests/"
fi

# get current open browser command
case $( uname -s ) in
  Darwin)  open=open;;
  MINGW*)  open=start;;
  CYGWIN*) open=cygstart;;
  MSYS*)   open="powershell.exe –NoProfile Start";;
  *)       open=${BROWSER:-xdg-open};;
esac

# open it in a browser
$open "$url" &> /dev/null
exit 0
